2025-05-11 11:27:18,721 - root - INFO - Logging initialized. Log file: /app/cache/error_logs/scraper_20250511_112718.log
2025-05-11 11:27:18,724 - __main__ - INFO - Starting financial report pipeline in mode 'all'
2025-05-11 11:27:18,728 - __main__ - INFO - Starting Financial Report scraper...
2025-05-11 11:27:18,774 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f88b0d4f370>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
2025-05-11 11:27:18,777 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f88b0d4ee90>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
2025-05-11 11:27:18,780 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f88b0d4f520>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
2025-05-11 11:27:18,784 - __main__ - INFO - Financial Report scraper completed. Scraped 0 reports.
2025-05-11 11:27:18,786 - __main__ - INFO - Starting Financial Report ingestion...
2025-05-11 11:27:18,810 - src.ingestion.financial_ingestion - INFO - Loading data from JSON file...
2025-05-11 11:27:18,819 - src.ingestion.financial_ingestion - WARNING - No data found in /app/cache/financial_reports/financial_reports.json
2025-05-11 11:27:18,820 - __main__ - INFO - Financial Report ingestion completed. Inserted 0 and updated 0 reports.
2025-05-11 11:27:18,821 - __main__ - INFO - Financial report pipeline completed successfully
